### ISSUE TITLE
使用发现一些问题

### ISSUE THREAD

**Issue by joewulf** [selden1992/console#1]
php artisan 回车后中文是乱码
php artisan make:migration users 回车后输出结果不换行
php artisan make:model 提示是 module\model 实际上是要 module/model
其他的暂时没用

**Comment by joewulf** [comment]
另外能不能实现model分层的make?

**Comment by joewulf** [comment]
另外如果migration要修改表的命令应该怎么打？
还是要在文件里面修改

**Comment by ctfang** [comment]
你用哪个分支? fds

**Comment by joewulf** [comment]
console/src/Extend/Help.php
删除了iconv就没乱码了
版本应该是 "selden1992/console":"dev-tp5.0"

**Comment by ctfang** [comment]
我没试过乱码,中文都是gbk的,migration修改表只能在文件里面改,我感觉那样更快,
如果你使用5.0版本,那个目录已经够清晰,   你可以注册自己的命令,覆盖旧的 make:model

**Comment by ctfang** [comment]
你可以push代码上来啊,我没有时间去维护,  目前的功能已经比官方的多了,
所有生成的文件,都可配置

**Comment by ctfang** [comment]
其实后面我还想加 crontab 的命令的,但是现在是另开artisan 入口文件,不是用官方自带think入口
数据迁移功能只支持mysql数据库
